import Head from 'next/head';
import Main from '../components/Main';
import About from '../components/About';
import Projects from '../components/Projects';

export default function Home() {
	return (
		<div>
			<Head>
				<title>Minjon | Jnr Developer</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/icon.svg' />
				<script
					async
					src='https://www.googletagmanager.com/gtag/js?id=G-5HC8CCLQDN'
				></script>
				<script>
					window.dataLayer = window.dataLayer || []; function gtag()
					{dataLayer.push(arguments)}
					gtag('js', new Date()); gtag('config', 'G-5HC8CCLQDN');
				</script>
			</Head>
			<Main />
			<About />
			<Projects />
		</div>
	);
}
