import Head from 'next/head';
import FirstPage from '../components/Home';

export default function Home() {
	return (
		<div>
			<Head>
				<title>Minjon | Jnr Developer</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/icon.svg' />
			</Head>
			<FirstPage />
			<div className='grid h-screen place-items-center relative'>
				<h1 className='text-gray-700'>
					Hi! I'm Minjon Holtzhausen
					<br />
					<p className='pt-6 text-3xl sm:text-4xl font-[sans-serif] text-[#9984D4]'>
						Junior Web Developer
					</p>
				</h1>
			</div>
		</div>
	);
}
