import React from 'react';
import WeatherApp from '../public/assets/projects/weatherApp.png';
import ItunesApp from '../public/assets/projects/itunes-app.png';
import Minesweeper from '../public/assets/projects/minesweeper.png';
import NetflixClone from '../public/assets/projects/netflix-clone.png';
import ComingSoon from '../public/assets/projects/coming-soon.png';
import ProjectItem from '../components/ProjectItems';
import Head from 'next/head';

const Projects = () => {
	return (
		<div id='projects' className='w-full'>
			<Head>
				<title>Minjon | Projects</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/icon.svg' />
			</Head>

			<div className='mx-6 m-auto px-2 py-24'>
				<h1 className='font-sans font-[500] text-gray-700 pb-8'>My Projects</h1>
				<div className='grid md:grid-cols-4 gap-8'>
					<ProjectItem
						title='Weather App'
						languages='Reactjs'
						bgImage={WeatherApp}
						projectURL='https://weather-app010.herokuapp.com/'
						aboutProject='This is one of my very first projects making use of APIs. It is a pretty simple application which displays the current weather of a specified area.'
					/>
					<ProjectItem
						title='Minesweeper'
						languages='Reactjs | Tailwind'
						bgImage={Minesweeper}
						projectURL='https://reactjs-minesweeper.vercel.app/'
						aboutProject='The app pretty much works like the original Minesweeper is intended to. This project was a challenging task to complete and had me stuck researching aspects of the porject for days on end.'
					/>
					<ProjectItem
						title='Netflix Clone'
						languages='TypeScript | Nextjs | Tailwind'
						bgImage={NetflixClone}
						projectURL='https://nextjs-netflix-app.vercel.app/'
						aboutProject='This project was as one of my Capstone Projects at HyperionDev. When I first created this clone, I only created the main part of a movie searching app. After I completed the course I revisited the project and added user sign up and account options functionalities using Stripe.'
					/>
					<div className='opacity-60'>
						<ProjectItem
							title='Online Store'
							languages='TBD...'
							bgImage={ComingSoon}
							projectURL=''
							aboutProject='I am currently busy with this project and it will be available soon.'
						/>
					</div>
				</div>
			</div>
		</div>
	);
};

export default Projects;
